### ISSUE TITLE
License

### ISSUE THREAD

**Issue by daytonlowell** [Skyrpex/ractive-components-bootstrap-modal#1]
I was just curious, what is the license for this project? Thanks.

**Comment by skyrpex** [comment]
Hi there. I just added a [license](https://github.com/skyrpex/ractive-components-bootstrap-modal/blob/master/LICENSE). AFAIK, MIT suits everyone's needs, right?

Honestly, I don't care about the license :)

**Comment by daytonlowell** [comment]
Thanks!
